---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    
 
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: launch-wizard-1
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: 1
         vpc_subnet_id: subnet-0b375748e7b7d9d00
         assign_public_ip: no
      register: ec2

