---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    
 
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: launch-wizard-1
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: 1
         vpc_subnet_id: subnet-0b375748e7b7d9d00
         assign_public_ip: no
      register: ec2






Note : Variable passing and lauching in pvt subnet 
 ansible-playbook -i ec2.py instance2.yml -e instance_type=t2.micro -e image=ami-05acd51c736cba473 -e region=us-east-1 -e keypair=think-data -e tag_Name=mysql-server -e tag_Service=mysql --extra-vars='ansible_python_interpreter=/usr/bin/python'
